name: Mining pro application deployment

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:

            - name: checkout code
              uses: actions/checkout@v4

            - name: setup java
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribuation: 'terminal'

            - name: build and panckage
              run: mvn clean package

            